name: cp-docker-utils
lang: unknown
lang_version: unknown
git:
  enable: true
codeowners:
  enable: true
renovatebot:
  enable: true
  automerge:
    enable: true
make:
  enable: true
  enable_updates: true
semaphore:
  enable: true
  pipeline_enable: false
